/**
 * Curated metadata — the AI namespace, part three.
 * Chips, composer controls and the icon treatment layer.
 */

export const ai3 = {

  'ai-chip-brief': {
    tier: 'atoms', category: 'AI', status: 'stable',
    intent: 'Whether an agent task brief is ready to run — and whether a human still has to say yes.',
    description: 'A status chip for agent task briefs: default, ready, missing, edited, waiting-approval, running. The status word renders as text beside the label, never as colour alone.',
    whenToUse: ['In a list of agent task briefs', 'Wherever readiness to execute must be scannable', 'Before an agent run is triggered'],
    whenNotToUse: ['For execution state once running — use ai:ai-queue-badge', 'As a general badge — use ui:badge', 'As a button'],
    anatomy: [{ part: 'Label', role: 'The brief name' }, { part: 'Status text', role: 'Appended after a separator. The accessible value.' }],
    variantGuidance: {
      default: 'Draft. Not yet complete.',
      ready: 'All inputs present. Can run.',
      missing: 'Required information absent.',
      edited: 'A human changed the agent-generated brief.',
      'waiting-approval': 'The state that matters — a human must approve before it runs.',
      running: 'Executing now.',
    },
    states: [
      { name: 'Draft', trigger: 'status="default"', note: 'Muted' },
      { name: 'Ready', trigger: 'status="ready"', note: 'Green tint' },
      { name: 'Missing information', trigger: 'status="missing"', note: 'Destructive tint' },
      { name: 'Edited', trigger: 'status="edited"', note: 'AI surface tint' },
      { name: 'Waiting for approval', trigger: 'status="waiting-approval"', note: 'Signal tint' },
      { name: 'Running', trigger: 'status="running"', note: 'AI surface tint' },
    ],
    a11y: {
      role: 'none', handledByRadix: false,
      keyboard: [],
      requiredAttributes: ['label'],
      notes: ['The status word appears both visually and in an sr-only span, so the tint is never the sole carrier of meaning.'],
    },
    agentRules: ['Never a button.', 'waiting-approval must mean a human genuinely has to approve.', 'Use ai:ai-queue-badge once it is executing.'],
    forbiddenUsage: ['Interactive use', 'Colour-only status', 'Generic badging'],
    related: [{ id: 'ai:ai-queue-badge', note: 'Execution state' }, { id: 'ui:badge', note: 'Generic status' }],
    examples: [{ title: 'Awaiting approval', code: '<AIChipBrief status="waiting-approval" label="Q4 territory rebalance" />' }],
    experienceMetadata: {
      experienceMode: ['AI Led'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution', 'Approval'],
      humanGestureRequired: false,
      reversible: 'not-applicable',
    },
  },

  'ai-chip-handoff': {
    tier: 'atoms', category: 'AI', status: 'stable',
    intent: 'Show the moment accountability changed hands.',
    description: 'A directional pill naming the source and target of a handoff: agent to agent, agent to human, human to agent, system to agent, or failed.',
    whenToUse: ['In an agent activity log or timeline', 'When work transfers between agents or between an agent and a person', 'To make it clear who is currently responsible'],
    whenNotToUse: ['As a general direction indicator', 'When no actual transfer occurred', 'As a button'],
    anatomy: [
      { part: 'From', role: 'Source icon and name' },
      { part: 'Arrow', role: 'Direction, aria-hidden' },
      { part: 'To', role: 'Target icon and name' },
    ],
    variantGuidance: {
      'agent-to-agent': 'One agent passed to another. AI tint.',
      'agent-to-human': 'The machine handed back. Signal tint — a person now owns it.',
      'human-to-agent': 'A person delegated. AI tint.',
      'system-to-agent': 'Automated dispatch. Neutral tint.',
      failed: 'The handoff did not complete. Destructive tint.',
    },
    states: [
      { name: 'Agent to agent', trigger: 'direction="agent-to-agent"', note: 'AI surface' },
      { name: 'Agent to human', trigger: 'direction="agent-to-human"', note: 'Signal — escalation' },
      { name: 'Human to agent', trigger: 'direction="human-to-agent"', note: 'AI surface' },
      { name: 'System to agent', trigger: 'direction="system-to-agent"', note: 'Neutral' },
      { name: 'Failed', trigger: 'direction="failed"', note: 'Destructive — nobody picked it up' },
    ],
    a11y: {
      role: 'none', handledByRadix: false,
      keyboard: [],
      requiredAttributes: ['fromLabel and toLabel'],
      notes: ['Both party names are visible text, so the icons carry no unique meaning.', 'An sr-only suffix distinguishes a completed handoff from a failed one.'],
    },
    agentRules: ['Only render for real transfers.', 'Name both parties specifically.', 'agent-to-human means a person is now accountable — do not use it loosely.'],
    forbiddenUsage: ['Decorative direction indicators', 'Unnamed parties', 'Interactive use'],
    related: [{ id: 'ai:ai-agent-stack', note: 'Who is working now' }, { id: 'ai:ai-agent-work-note', note: 'What they did' }],
    examples: [{ title: 'Escalation', code: '<AIChipHandoff direction="agent-to-human" fromLabel="Research agent" toLabel="Dana" />' }],
    experienceMetadata: {
      experienceMode: ['AI Led'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution', 'Audit trail'],
      humanGestureRequired: false,
      reversible: 'not-applicable',
    },
  },

  'ai-chip-memory': {
    tier: 'atoms', category: 'AI', status: 'stable',
    intent: 'Tell the user when the system is drawing on something it learned earlier.',
    description: 'An inline label for remembered context: using-memory, previous-context, memory-available, memory-ignored, memory-removed.',
    whenToUse: ['When a response depends on remembered context', 'To show what memory is available but unused', 'To confirm that memory was ignored or removed'],
    whenNotToUse: ['When no memory is in play', 'As a general tag — use ui:badge', 'To imply memory the system does not actually have'],
    anatomy: [{ part: 'Icon', role: 'Variant glyph, aria-hidden' }, { part: 'Prefix', role: 'sr-only — "Using memory:" etc.' }, { part: 'Label', role: 'What is remembered' }],
    variantGuidance: {
      'using-memory': 'Actively drawing on it now. Signal tint, because the user should notice.',
      'previous-context': 'Carried from earlier in the session. Neutral.',
      'memory-available': 'Could be used, currently is not.',
      'memory-ignored': 'Deliberately not used this time.',
      'memory-removed': 'Deleted. Struck through.',
    },
    states: [
      { name: 'Using memory', trigger: 'variant="using-memory"', note: 'Signal tint' },
      { name: 'Previous context', trigger: 'variant="previous-context"', note: 'Neutral' },
      { name: 'Memory available', trigger: 'variant="memory-available"', note: 'AI surface' },
      { name: 'Memory ignored', trigger: 'variant="memory-ignored"', note: 'Transparent, muted' },
      { name: 'Memory removed', trigger: 'variant="memory-removed"', note: 'Struck through' },
    ],
    a11y: {
      role: 'none', handledByRadix: false,
      keyboard: [],
      requiredAttributes: ['label'],
      notes: [
        'The sr-only prefix supplies the variant meaning, so the icon and tint are never the only signal.',
        'memory-removed uses line-through, which is not announced by screen readers — the prefix carries it instead.',
      ],
    },
    agentRules: [
      'Only render when memory is genuinely involved.',
      'Name what is remembered, specifically.',
      'Forgetting should be as visible as remembering — do not silently drop the removed and ignored variants.',
    ],
    forbiddenUsage: ['Implying memory that does not exist', 'Generic tagging', 'Hiding memory use'],
    related: [{ id: 'ai:ai-agent-work-note', note: 'What the agent did with it' }, { id: 'ui:badge', note: 'Generic tags' }],
    examples: [{ title: 'Active memory', code: '<AIChipMemory variant="using-memory" label="Your Q3 pipeline preferences" />' }],
    experienceMetadata: {
      experienceMode: ['Adaptive', 'AI Assisted'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution', 'Rationale disclosure', 'Audit trail'],
      humanGestureRequired: false,
      reversible: 'not-applicable',
    },
  },

  'ai-chip-quick': {
    tier: 'atoms', category: 'AI', status: 'stable',
    intent: 'Offer a starting point so the user does not face an empty box.',
    description: 'A suggested prompt chip. Tapping one composes a message; it never executes. An optional special variant carries the gradient for an "All prompts" call to action.',
    whenToUse: ['Idle state of a composer', 'Suggested follow-ups after a response', 'Reducing the cost of starting'],
    whenNotToUse: [
      'For chips that perform an action — that is a different, higher-autonomy component',
      'More than about five at once',
      'As a filter chip — use ui:toggle',
    ],
    anatomy: [{ part: 'Icon', role: 'Optional leading glyph, aria-hidden' }, { part: 'Label', role: 'The suggested prompt' }],
    states: [
      { name: 'Default', trigger: 'Rest', note: 'Card background, AI border' },
      { name: 'Special', trigger: 'isSpecial', note: 'Gradient fill. One per group at most.' },
      { name: 'Focus-visible', trigger: 'Keyboard focus', note: 'ring-2 ring-ai-accent' },
    ],
    a11y: {
      role: 'button', handledByRadix: false,
      keyboard: ['Enter or Space — compose the prompt'],
      requiredAttributes: ['label'],
      notes: [
        'Composing rather than executing is the whole safety property: the user still sees and sends the message.',
        'The icon is decorative; the label carries the meaning.',
      ],
    },
    agentRules: [
      'Compose, never execute.',
      'Five chips maximum.',
      'One isSpecial chip per group.',
      'Write labels as the user would phrase the request.',
    ],
    forbiddenUsage: ['Executing on click', 'More than five chips', 'Use as filter chips'],
    related: [{ id: 'ui:toggle', note: 'Filter chips' }, { id: 'ai:ai-dialog-button', note: 'Composer toolbar controls' }],
    examples: [{ title: 'Idle suggestions', code: '<AIChipQuick icon={Search} label="Find at-risk accounts" onClick={() => compose("Find at-risk accounts")} />' }],
    experienceMetadata: {
      experienceMode: ['AI Assisted'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution'],
      humanGestureRequired: true,
      reversible: 'always',
    },
  },

  'ai-dialog-button': {
    tier: 'atoms', category: 'AI', status: 'stable',
    intent: 'A quiet control in the composer toolbar that does not compete with the message.',
    description: 'A ghost toolbar button in three shapes: icon-only (a 34px circle), icon plus label, or label plus a trailing chevron for dropdowns.',
    whenToUse: ['Composer toolbar controls — attach, skills, agent mode, microphone', 'Any low-emphasis control beside an input'],
    whenNotToUse: ['Primary actions — use ai:ai-button', 'Outside a composer context', 'Icon-only without an accessible name'],
    anatomy: [
      { part: 'Icon', role: 'Leading glyph. Sole content makes it a 34px circle.' },
      { part: 'Label', role: '13px medium' },
      { part: 'Trailing icon', role: 'Usually a chevron. Its presence adds aria-expanded.' },
    ],
    states: [
      { name: 'Default', trigger: 'Rest', note: 'Transparent' },
      { name: 'Hover', trigger: 'Pointer over', note: 'bg-accent' },
      { name: 'Open', trigger: 'isOpen', note: 'bg-accent held; aria-expanded true when a trailing icon is present' },
      { name: 'Disabled', trigger: 'disabled', note: 'opacity 0.42' },
    ],
    a11y: {
      role: 'button', handledByRadix: false,
      keyboard: ['Enter or Space — activate'],
      requiredAttributes: ['aria-label when icon-only'],
      notes: [
        'Icon-only with no aria-label logs a development warning — it has no accessible name at all.',
        'aria-expanded is set only when a trailing icon is present, since that is what signals a dropdown.',
        'At 34px it is under the 44px touch guideline. Give the toolbar padding on touch surfaces.',
      ],
    },
    agentRules: [
      'Icon-only requires aria-label.',
      'Set isOpen when it owns an open menu.',
      'Use ai:ai-button for anything primary.',
      'Pair icon-only controls with ui:tooltip.',
    ],
    forbiddenUsage: ['Icon-only with no accessible name', 'Primary actions', 'Use outside a composer'],
    related: [{ id: 'ai:ai-button', note: 'Primary AI actions' }, { id: 'ui:tooltip', note: 'Naming icon-only controls' }, { id: 'ui:dropdown-menu', note: 'What a trailing chevron opens' }],
    examples: [{ title: 'Toolbar control', code: '<AIDialogButton icon={<Paperclip />} aria-label="Attach a file" onClick={attach} />' }],
    experienceMetadata: {
      experienceMode: ['AI Assisted'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution'],
      humanGestureRequired: true,
      reversible: 'not-applicable',
    },
  },

  'ai-text-link': {
    tier: 'atoms', category: 'AI', status: 'beta',
    intent: 'An inline link inside AI prose whose label stands on its own.',
    description: 'An explainability link with six variants and three tones. Renders an anchor when href is given and a button otherwise, so disclosure actions are announced correctly.',
    whenToUse: ['Citations and source links inside AI prose', 'Inline disclosure triggers', 'Opening an audit record in a new tab'],
    whenNotToUse: [
      'The standard rationale entry — use ai:ai-why-this-link, which has the right defaults',
      'General product links — use a plain anchor',
      'Disabled without a reason',
    ],
    anatomy: [
      { part: 'Leading icon', role: 'Optional, aria-hidden. Replaced by a spinner while loading.' },
      { part: 'Label', role: 'Must make the purpose clear without the icon' },
      { part: 'Chevron', role: 'For disclosure variants; rotates when expanded' },
      { part: 'External mark', role: 'With an sr-only "opens in a new tab"' },
    ],
    variantGuidance: {
      text: 'Label alone.',
      'icon-leading': 'Icon plus label. The common case.',
      chevron: 'Label plus chevron — expands inline content.',
      'icon-chevron': 'Full anatomy for a disclosure trigger.',
      external: 'Opens a source record in a new tab.',
    },
    states: [
      { name: 'Default', trigger: 'Rest', note: 'Tone colour, underline on hover' },
      { name: 'Expanded', trigger: 'expanded', note: 'Chevron rotated; aria-expanded set' },
      { name: 'Loading', trigger: 'loading', note: 'Spinner replaces the leading icon' },
      { name: 'Disabled', trigger: 'disabled', note: 'Muted and inert. disabledReason becomes the title and accessible name.' },
    ],
    a11y: {
      role: 'link or button', handledByRadix: false,
      keyboard: ['Enter — activate', 'Space — activate when rendered as a button'],
      requiredAttributes: ['label', 'disabledReason when disabled'],
      notes: [
        'No href means it renders a button, because a disclosure action is not navigation. This is what makes Space work and keeps it out of the link list.',
        'External links carry rel="noreferrer noopener" and an sr-only "opens in a new tab".',
        'Disabling without disabledReason logs a development warning — removing an affordance without explaining why is a dead end.',
        'The attention tone is reserved for escalation, approval and staleness. Do not use it for emphasis.',
      ],
    },
    agentRules: [
      'The label must stand alone — an icon is never the only signal of purpose.',
      'Always pair disabled with disabledReason.',
      'Reserve the attention tone for escalation, approval and staleness.',
      'Use ai:ai-why-this-link for the standard rationale entry.',
    ],
    forbiddenUsage: ['Icon-only meaning', 'Disabled with no reason', 'Attention tone for emphasis'],
    related: [{ id: 'ai:ai-why-this-link', note: 'The standard rationale entry' }, { id: 'ui:button', note: 'variant="link" for standard links' }],
    examples: [{ title: 'Source citation', code: '<AITextLink variant="external" label="Q3 pipeline report" href="/reports/q3" />' }],
    experienceMetadata: {
      experienceMode: ['AI Assisted', 'Adaptive', 'AI Led'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution', 'Rationale disclosure'],
      humanGestureRequired: false,
      reversible: 'not-applicable',
    },
  },

  'ai-icon': {
    tier: 'atoms', category: 'AI', status: 'beta',
    intent: 'A treatment layer over standard icons — not a new icon set.',
    description: 'Wraps any icon component with sizing, colour treatment, semantic tone, an optional container and motion. Governed by the 60-30-10 rule.',
    whenToUse: ['Applying AI identity colour to a standard icon', 'Semantic tones for agentic states', 'Motion on an icon that reflects real activity'],
    whenNotToUse: [
      'As a source of new icons — pass in an existing one',
      'Applying treatment="ai" broadly; if every icon is an AI icon, none is',
      'Motion that does not track real work',
    ],
    anatomy: [{ part: 'Wrapper', role: 'Carries sizing, colour, container and motion' }, { part: 'Icon', role: 'The component you pass in' }],
    variantGuidance: {
      neutral: 'About 60% of icons on an AI surface. The default.',
      ai: 'About 10%. The identity colour. Scarce by design.',
      'ai-contained': 'A rounded container for prominent AI identity.',
      semantic: 'About 30%. Use with tone for state.',
      'orange-signal': 'Review and escalation only.',
    },
    sizeGuidance: {
      xs: '12px. Inline metadata.',
      sm: '16px. Most contexts.',
      md: '20px. The standard AI icon.',
      lg: '24px. Prominent identity.',
      xl: '32px. Hero and empty states only.',
    },
    states: [
      { name: 'Decorative', trigger: 'decorative', note: 'aria-hidden. Correct when adjacent text carries the meaning.' },
      { name: 'Labelled', trigger: 'label', note: 'role="img" with an accessible name' },
      { name: 'Spinning', trigger: 'motion="spin"', note: 'Respects reduced motion' },
      { name: 'Pulsing', trigger: 'motion="pulse"', note: 'Respects reduced motion' },
    ],
    a11y: {
      role: 'img or none', handledByRadix: false,
      keyboard: [],
      requiredAttributes: ['Either label or decorative — one of the two, always'],
      notes: [
        'Setting neither logs a development warning. An icon with meaning and no name is invisible.',
        'All motion carries motion-reduce:animate-none.',
        'Motion must reflect real activity. A permanently spinning icon is noise that trains users to ignore it.',
      ],
    },
    agentRules: [
      'Set either label or decorative on every instance.',
      'Follow 60-30-10 — treatment="ai" is scarce.',
      'Motion must track real work.',
      'Reserve orange-signal for review and escalation.',
    ],
    forbiddenUsage: ['Neither labelled nor decorative', 'Decorative motion', 'Overusing the AI treatment'],
    related: [{ id: 'ai:ai-avatar', note: 'Agent identity, not iconography' }],
    examples: [{ title: 'Semantic state', code: '<AIIcon icon={ShieldAlert} treatment="semantic" tone="escalated" label="Escalated to a person" />' }],
    experienceMetadata: {
      experienceMode: ['AI Assisted', 'Adaptive', 'AI Led'],
      aiBehavior: ['Suggest'],
      accountability: ['Attribution'],
      humanGestureRequired: false,
      reversible: 'not-applicable',
    },
    gaps: ['The handoff-trail, completion-settle, nudge, shimmer and alert-ring motions from the source system are not implemented. Only spin and pulse.'],
  },
}
