/**
 * Curated metadata — Navigation, disclosure and notification.
 */

export const navigation = {

  tabs: {
    tier: 'organisms', category: 'Navigation', status: 'stable',
    intent: 'Switch between peer views of the same subject, where only one is relevant at a time.',
    description: 'Radix Tabs with roving focus and automatic activation. Content is unmounted when inactive by default.',
    whenToUse: ['Alternative views of one object — Overview, Activity, Settings', 'Peer sections where the user rarely needs two at once', 'Two to six sections with short labels'],
    whenNotToUse: [
      'Sequential steps — use a stepper or separate routes; tabs imply order does not matter',
      'Content the user needs to compare side by side',
      'More than about six sections, or labels that will not fit',
      'Content that should be linkable — unless you sync the active tab to the URL',
    ],
    compound: {
      root: 'Tabs',
      parts: [
        { name: 'TabsList', parent: 'Tabs', required: true, note: 'The tablist container' },
        { name: 'TabsTrigger', parent: 'TabsList', required: true, note: 'value must match a TabsContent' },
        { name: 'TabsContent', parent: 'Tabs', required: true, note: 'Unmounted when inactive unless forceMount is set' },
      ],
    },
    states: [
      { name: 'Inactive', trigger: 'Not the current value', note: 'Transparent trigger; content unmounted' },
      { name: 'Active', trigger: 'Matches the current value', note: 'bg-background with shadow-sm on the trigger' },
      { name: 'Focus-visible', trigger: 'Keyboard focus', note: 'ring-2 ring-ring ring-offset-2' },
      { name: 'Disabled', trigger: 'disabled on a trigger', note: 'opacity-50, skipped by arrow keys' },
    ],
    a11y: {
      role: 'tablist', handledByRadix: true,
      keyboard: ['Arrow keys — move between and activate tabs', 'Tab — move into the panel', 'Home/End — first or last tab'],
      requiredAttributes: ['aria-label on TabsList when there is no visible heading'],
      notes: [
        'Radix wires tablist, tab and tabpanel roles plus aria-selected and aria-controls.',
        'Activation is automatic: arrowing to a tab selects it. For expensive content use activationMode="manual" so arrow keys only move focus.',
        'Inactive content is unmounted, so form state inside a tab is lost on switch. Use forceMount if that matters.',
      ],
    },
    agentRules: [
      'Label the TabsList when no visible heading names it.',
      'Every trigger value must match a content value.',
      'Use activationMode="manual" when panels are expensive to render.',
      'Tabs are not steps. A wizard needs routes or a stepper.',
      'Sync to the URL if a tab should be shareable.',
    ],
    forbiddenUsage: ['Tabs as a wizard', 'Trigger with no matching content', 'More than six tabs'],
    related: [{ id: 'ui:accordion', note: 'Vertical disclosure, several open at once' }, { id: 'ui:toggle-group', note: 'Compact filter switching' }],
    examples: [{ title: 'Object views', code: '<Tabs defaultValue="overview">\n  <TabsList aria-label="Project views">\n    <TabsTrigger value="overview">Overview</TabsTrigger>\n    <TabsTrigger value="activity">Activity</TabsTrigger>\n  </TabsList>\n  <TabsContent value="overview">{/* … */}</TabsContent>\n  <TabsContent value="activity">{/* … */}</TabsContent>\n</Tabs>' }],
  },

  accordion: {
    tier: 'organisms', category: 'Disclosure', status: 'stable',
    intent: 'Let a long page stay scannable by collapsing detail the user can open on demand.',
    description: 'Radix Accordion in single or multiple mode, with an animated chevron and height transition.',
    whenToUse: ['FAQs', 'Long forms broken into optional sections', 'Settings groups most users will not open', 'Progressive disclosure of secondary detail'],
    whenNotToUse: [
      'Content most users need — hiding it costs more than the vertical space saves',
      'Fewer than three sections',
      'Peer views of one object — use ui:tabs',
      'Content that must be searchable in-page, since collapsed text is not findable by Ctrl+F',
    ],
    compound: {
      root: 'Accordion',
      parts: [
        { name: 'AccordionItem', parent: 'Accordion', required: true, note: 'Needs a unique value' },
        { name: 'AccordionTrigger', parent: 'AccordionItem', required: true, note: 'Renders a button inside an h3' },
        { name: 'AccordionContent', parent: 'AccordionItem', required: true },
      ],
    },
    states: [
      { name: 'Collapsed', trigger: 'Not in value', note: 'Content hidden; chevron pointing down' },
      { name: 'Expanded', trigger: 'In value', note: 'Content animates open; chevron rotates 180°' },
      { name: 'Focus-visible', trigger: 'Keyboard focus on a trigger', note: 'Focus ring on the trigger' },
      { name: 'Disabled', trigger: 'disabled on an item', note: 'opacity-50, not togglable' },
    ],
    a11y: {
      role: 'region', handledByRadix: true,
      keyboard: ['Enter or Space — toggle', 'Tab — move between triggers', 'Arrow keys — move between triggers'],
      requiredAttributes: ['type is required: "single" or "multiple"'],
      notes: [
        'Radix wraps each trigger in an h3 with a button inside, and wires aria-expanded and aria-controls.',
        'Collapsed content is removed from the DOM, so browser find-in-page will not reach it.',
        'type="single" with collapsible={false} means one section is always open — decide which.',
      ],
    },
    agentRules: [
      'type is required.',
      'Do not hide content most users need.',
      'Three or more sections, or use something else.',
      'Remember collapsed content is not findable by Ctrl+F.',
    ],
    forbiddenUsage: ['Accordion with no type', 'Hiding primary content', 'Fewer than three sections'],
    related: [{ id: 'ui:collapsible', note: 'A single disclosure with no group behaviour' }, { id: 'ui:tabs', note: 'Peer views' }],
    examples: [{ title: 'FAQ', code: '<Accordion type="single" collapsible>\n  <AccordionItem value="billing">\n    <AccordionTrigger>How does billing work?</AccordionTrigger>\n    <AccordionContent>Monthly, in arrears.</AccordionContent>\n  </AccordionItem>\n</Accordion>' }],
  },

  collapsible: {
    tier: 'molecules', category: 'Disclosure', status: 'stable',
    intent: 'One thing that opens and closes, with no group to coordinate.',
    description: 'Radix Collapsible, unstyled. Twelve lines: three re-exports with no classes applied.',
    whenToUse: ['A single show-more region', 'Advanced options below a form', 'A sidebar section that expands'],
    whenNotToUse: ['Several related sections — use ui:accordion, which handles the group and the heading semantics', 'Content that should be visible by default'],
    compound: {
      root: 'Collapsible',
      parts: [
        { name: 'CollapsibleTrigger', parent: 'Collapsible', required: true, note: 'Use asChild to supply your own button' },
        { name: 'CollapsibleContent', parent: 'Collapsible', required: true },
      ],
    },
    states: [
      { name: 'Closed', trigger: 'open={false}', note: 'Content hidden' },
      { name: 'Open', trigger: 'open={true}', note: 'Content revealed. No animation is applied by this component — add your own.' },
    ],
    a11y: {
      role: 'button with aria-expanded', handledByRadix: true,
      keyboard: ['Enter or Space — toggle'],
      requiredAttributes: ['A meaningful trigger label that reflects the action'],
      notes: [
        'Radix wires aria-expanded and aria-controls.',
        'This component applies no styling at all. The chevron, the animation and the spacing are all yours.',
        'The trigger label should say what will be revealed — "Advanced options", not "More".',
      ],
    },
    agentRules: ['Bring your own styling — nothing is applied.', 'Use ui:accordion for grouped sections.', 'Trigger labels name the content, not the gesture.'],
    forbiddenUsage: ['Using Collapsible for a group where Accordion belongs'],
    related: [{ id: 'ui:accordion', note: 'Grouped, styled, with heading semantics' }],
    examples: [{ title: 'Advanced options', code: '<Collapsible>\n  <CollapsibleTrigger asChild>\n    <Button variant="ghost" size="sm">Advanced options</Button>\n  </CollapsibleTrigger>\n  <CollapsibleContent className="space-y-2 pt-2">\n    {/* … */}\n  </CollapsibleContent>\n</Collapsible>' }],
    gaps: ['Entirely unstyled — no animation, chevron or spacing. Unlike every other component here, you supply all of it.'],
  },

  breadcrumb: {
    tier: 'molecules', category: 'Navigation', status: 'stable',
    intent: 'Show where this page sits in the hierarchy, and offer a way back up.',
    description: 'Semantic breadcrumb markup: nav, ordered list, links, and a current page marked with aria-current.',
    whenToUse: ['Hierarchies three or more levels deep', 'When users arrive from search and need orientation', 'File and folder structures'],
    whenNotToUse: [
      'Flat sites with no hierarchy',
      'As a step indicator for a wizard — breadcrumbs describe location, not progress',
      'When the hierarchy is only one level deep',
    ],
    compound: {
      root: 'Breadcrumb',
      parts: [
        { name: 'BreadcrumbList', parent: 'Breadcrumb', required: true, note: 'An ol' },
        { name: 'BreadcrumbItem', parent: 'BreadcrumbList', required: true, note: 'An li' },
        { name: 'BreadcrumbLink', parent: 'BreadcrumbItem', required: false, note: 'Use asChild with your router link' },
        { name: 'BreadcrumbPage', parent: 'BreadcrumbItem', required: false, note: 'The current page. Carries aria-current="page" and is not a link.' },
        { name: 'BreadcrumbSeparator', parent: 'BreadcrumbList', required: false, note: 'aria-hidden — decorative' },
        { name: 'BreadcrumbEllipsis', parent: 'BreadcrumbItem', required: false, note: 'Collapsed middle segments' },
      ],
    },
    states: [
      { name: 'Link', trigger: 'An ancestor level', note: 'hover:text-foreground' },
      { name: 'Current page', trigger: 'BreadcrumbPage', note: 'text-foreground, aria-current="page", not clickable' },
      { name: 'Collapsed', trigger: 'BreadcrumbEllipsis', note: 'Stands in for hidden middle levels' },
    ],
    a11y: {
      role: 'navigation', handledByRadix: false,
      keyboard: ['Tab through the links'],
      requiredAttributes: ['aria-label="Breadcrumb" on the nav — set by the component', 'aria-current="page" on the last item — set by BreadcrumbPage'],
      notes: [
        'The final item must be BreadcrumbPage, not BreadcrumbLink. Linking to the current page is a common and pointless error.',
        'Separators are aria-hidden so they are not read as content.',
        'BreadcrumbEllipsis is decorative. If the hidden levels matter, put them in a ui:dropdown-menu behind it.',
      ],
    },
    agentRules: ['The last item is always BreadcrumbPage.', 'Use asChild to integrate your router.', 'Put collapsed levels behind a real menu, not a bare ellipsis.', 'Not a wizard stepper.'],
    forbiddenUsage: ['Linking the current page', 'Breadcrumbs as a step indicator', 'Flat hierarchies'],
    related: [{ id: 'ui:navigation-menu', note: 'Primary site navigation' }, { id: 'ui:dropdown-menu', note: 'Revealing collapsed levels' }],
    examples: [{ title: 'Three levels', code: '<Breadcrumb>\n  <BreadcrumbList>\n    <BreadcrumbItem><BreadcrumbLink href="/">Home</BreadcrumbLink></BreadcrumbItem>\n    <BreadcrumbSeparator />\n    <BreadcrumbItem><BreadcrumbLink href="/projects">Projects</BreadcrumbLink></BreadcrumbItem>\n    <BreadcrumbSeparator />\n    <BreadcrumbItem><BreadcrumbPage>Apollo</BreadcrumbPage></BreadcrumbItem>\n  </BreadcrumbList>\n</Breadcrumb>' }],
  },

  pagination: {
    tier: 'molecules', category: 'Navigation', status: 'stable',
    intent: 'Move through a result set that is too large to show at once.',
    description: 'Semantic pagination markup using buttonVariants. Presentational only — the page state and routing are yours.',
    whenToUse: ['Paged tables and result lists', 'When the total count is known and useful', 'When users need to return to a specific page'],
    whenNotToUse: [
      'Feeds where infinite scroll suits the content better',
      'Fewer than about three pages',
      'When the total is unknown — use a simpler next-and-previous pair',
    ],
    compound: {
      root: 'Pagination',
      parts: [
        { name: 'PaginationContent', parent: 'Pagination', required: true, note: 'A ul' },
        { name: 'PaginationItem', parent: 'PaginationContent', required: true, note: 'An li' },
        { name: 'PaginationLink', parent: 'PaginationItem', required: false, note: 'isActive sets aria-current="page" and the outline variant' },
        { name: 'PaginationPrevious', parent: 'PaginationItem', required: false },
        { name: 'PaginationNext', parent: 'PaginationItem', required: false },
        { name: 'PaginationEllipsis', parent: 'PaginationItem', required: false, note: 'aria-hidden, with an sr-only "More pages"' },
      ],
    },
    states: [
      { name: 'Inactive page', trigger: 'Not the current page', note: 'Ghost variant' },
      { name: 'Active page', trigger: 'isActive', note: 'Outline variant with aria-current="page"' },
      { name: 'Boundary', trigger: 'First or last page', note: 'Disable previous or next yourself — the component does not' },
    ],
    a11y: {
      role: 'navigation', handledByRadix: false,
      keyboard: ['Tab through the links'],
      requiredAttributes: ['aria-label="pagination" on the nav — set by the component', 'aria-current="page" via isActive'],
      notes: [
        'Renders anchors. For client-side routing, use asChild with your router link.',
        'Previous and Next are not disabled at the boundaries automatically. Handle that yourself or they lead nowhere.',
        'Announce the page change in a live region — the content updates silently otherwise.',
      ],
    },
    agentRules: ['Disable previous and next at the boundaries yourself.', 'Set isActive on the current page.', 'Announce page changes in a live region.', 'Use asChild for client-side routing.'],
    forbiddenUsage: ['Enabled previous on page one', 'No current-page indication', 'Silent page changes'],
    related: [{ id: 'ui:table', note: 'The usual companion' }, { id: 'ui:button', note: 'buttonVariants supplies the styling' }],
    examples: [{ title: 'Paged results', code: '<Pagination>\n  <PaginationContent>\n    <PaginationItem>\n      <PaginationPrevious href="#" aria-disabled={page === 1} />\n    </PaginationItem>\n    <PaginationItem><PaginationLink href="#" isActive>1</PaginationLink></PaginationItem>\n    <PaginationItem><PaginationLink href="#">2</PaginationLink></PaginationItem>\n    <PaginationItem><PaginationEllipsis /></PaginationItem>\n    <PaginationItem><PaginationNext href="#" /></PaginationItem>\n  </PaginationContent>\n</Pagination>' }],
    gaps: ['No page-state logic, no boundary disabling, no live-region announcement. All presentational.'],
  },

  'navigation-menu': {
    tier: 'organisms', category: 'Navigation', status: 'stable',
    intent: 'Primary site navigation, with room for a rich panel under each top-level item.',
    description: 'Radix NavigationMenu with an animated viewport and an indicator. Built for websites rather than applications.',
    whenToUse: ['Marketing site headers', 'Mega-menus with grouped links and descriptions', 'Primary navigation with two levels'],
    whenNotToUse: [
      'Application menus — use ui:menubar or a toolbar with ui:dropdown-menu',
      'Actions rather than navigation',
      'Mobile — collapse to a ui:sheet instead',
      'Flat navigation with no second level — plain links are better',
    ],
    compound: {
      root: 'NavigationMenu',
      parts: [
        { name: 'NavigationMenuList', parent: 'NavigationMenu', required: true },
        { name: 'NavigationMenuItem', parent: 'NavigationMenuList', required: true },
        { name: 'NavigationMenuTrigger', parent: 'NavigationMenuItem', required: false, note: 'For items with a panel' },
        { name: 'NavigationMenuContent', parent: 'NavigationMenuItem', required: false, note: 'The panel' },
        { name: 'NavigationMenuLink', parent: 'NavigationMenuItem | NavigationMenuContent', required: false, note: 'Use asChild with your router link' },
        { name: 'NavigationMenuIndicator', parent: 'NavigationMenuList', required: false, note: 'The arrow pointing at the active trigger' },
        { name: 'NavigationMenuViewport', parent: 'NavigationMenu', required: false, note: 'Rendered automatically' },
      ],
    },
    states: [
      { name: 'Closed', trigger: 'Rest', note: 'Triggers visible' },
      { name: 'Open', trigger: 'Hover or focus on a trigger', note: 'Viewport animates to the panel size' },
      { name: 'Active link', trigger: 'data-active', note: 'bg-accent/50' },
    ],
    a11y: {
      role: 'navigation', handledByRadix: true,
      keyboard: ['Tab — move between top-level items', 'Enter or Space — open a panel', 'Arrow keys — move within a panel', 'Escape — close'],
      requiredAttributes: ['An accessible name on the nav when there is more than one on the page'],
      notes: [
        'Opens on hover as well as focus, which is right for site navigation and wrong for actions.',
        'Use navigationMenuTriggerStyle() for links that must match trigger styling.',
        'On mobile this pattern does not work. Swap to ui:sheet below the breakpoint.',
      ],
    },
    agentRules: ['Navigation only — never actions.', 'Use asChild for router integration.', 'Provide a ui:sheet fallback on mobile.', 'Name the nav when the page has several.'],
    forbiddenUsage: ['Actions in a navigation menu', 'Mobile usage with no fallback', 'Application menus'],
    related: [{ id: 'ui:menubar', note: 'Application menu bar' }, { id: 'ui:sheet', note: 'Mobile navigation' }, { id: 'ui:breadcrumb', note: 'Location within the hierarchy' }],
    examples: [{ title: 'Two-level nav', code: '<NavigationMenu>\n  <NavigationMenuList>\n    <NavigationMenuItem>\n      <NavigationMenuTrigger>Products</NavigationMenuTrigger>\n      <NavigationMenuContent>\n        <ul className="grid w-[400px] gap-3 p-4">\n          <li><NavigationMenuLink asChild><a href="/a">Analytics</a></NavigationMenuLink></li>\n        </ul>\n      </NavigationMenuContent>\n    </NavigationMenuItem>\n  </NavigationMenuList>\n</NavigationMenu>' }],
  },

  sidebar: {
    tier: 'templates', category: 'Layout', status: 'stable',
    intent: 'A complete application navigation shell — collapsible, persistent, responsive, and keyboard-reachable.',
    description: 'The largest component in the inventory at 774 lines. Provider, trigger, rail, inset, header, footer, groups, menus, submenus, badges and skeletons. Collapse state persists in a cookie; on mobile it becomes a ui:sheet.',
    whenToUse: ['Application shells with persistent navigation', 'Dashboards and admin interfaces', 'Any layout needing a collapsible nav that survives reloads'],
    whenNotToUse: [
      'Marketing sites — use ui:navigation-menu',
      'Simple layouts where a header is enough',
      'When you only need a static panel — this brings a provider, a cookie and a keyboard shortcut',
    ],
    compound: {
      root: 'SidebarProvider',
      parts: [
        { name: 'SidebarProvider', parent: null, required: true, note: 'Owns open state, the cookie and the Cmd+B shortcut. Nothing works without it.' },
        { name: 'Sidebar', parent: 'SidebarProvider', required: true, note: 'side, variant and collapsible props' },
        { name: 'SidebarInset', parent: 'SidebarProvider', required: false, note: 'The main content region beside the sidebar' },
        { name: 'SidebarTrigger', parent: 'SidebarProvider', required: false, note: 'The toggle button' },
        { name: 'SidebarRail', parent: 'Sidebar', required: false, note: 'The thin drag-to-toggle edge' },
        { name: 'SidebarHeader', parent: 'Sidebar', required: false },
        { name: 'SidebarContent', parent: 'Sidebar', required: true },
        { name: 'SidebarFooter', parent: 'Sidebar', required: false },
        { name: 'SidebarGroup', parent: 'SidebarContent', required: false },
        { name: 'SidebarGroupLabel', parent: 'SidebarGroup', required: false },
        { name: 'SidebarGroupContent', parent: 'SidebarGroup', required: false },
        { name: 'SidebarMenu', parent: 'SidebarGroupContent', required: false, note: 'A ul' },
        { name: 'SidebarMenuItem', parent: 'SidebarMenu', required: true, note: 'An li' },
        { name: 'SidebarMenuButton', parent: 'SidebarMenuItem', required: false, note: 'isActive marks the current route. tooltip shows when collapsed.' },
        { name: 'SidebarMenuSub', parent: 'SidebarMenuItem', required: false },
        { name: 'SidebarMenuAction', parent: 'SidebarMenuItem', required: false, note: 'A secondary action on hover' },
        { name: 'SidebarMenuBadge', parent: 'SidebarMenuItem', required: false },
        { name: 'SidebarMenuSkeleton', parent: 'SidebarMenu', required: false },
        { name: 'SidebarSeparator', parent: 'Sidebar', required: false },
      ],
    },
    states: [
      { name: 'Expanded', trigger: 'Default', note: 'Full width, labels visible' },
      { name: 'Collapsed (icon)', trigger: 'collapsible="icon"', note: 'Icons only. SidebarMenuButton tooltips become the labels.' },
      { name: 'Collapsed (offcanvas)', trigger: 'collapsible="offcanvas"', note: 'Slides entirely out of view' },
      { name: 'Mobile', trigger: 'Below the breakpoint', note: 'Renders as a ui:sheet regardless of the collapsed state' },
    ],
    a11y: {
      role: 'complementary', handledByRadix: false,
      keyboard: ['Cmd/Ctrl+B — toggle, bound by the provider', 'Tab through menu items', 'Enter — activate'],
      requiredAttributes: ['tooltip on SidebarMenuButton when collapsible="icon"', 'isActive plus aria-current on the active route'],
      notes: [
        'When collapsed to icons, the tooltip prop is the only accessible name a menu button has. Omitting it makes the collapsed sidebar unusable.',
        'The Cmd+B shortcut is registered globally by the provider. Check it does not collide with your editor surfaces.',
        'Uses its own --sidebar-* token scale, deliberately distinct from the page palette.',
      ],
    },
    agentRules: [
      'SidebarProvider must wrap everything, including SidebarInset.',
      'Always set the tooltip prop on SidebarMenuButton when collapsible="icon".',
      'Mark the active route with isActive.',
      'Use the --sidebar-* tokens, not the page tokens.',
      'Mobile renders as a Sheet — verify both.',
    ],
    forbiddenUsage: ['Sidebar without SidebarProvider', 'Icon-collapsible menu buttons with no tooltip', 'Page tokens instead of sidebar tokens', 'Using Sidebar for marketing navigation'],
    related: [{ id: 'ui:sheet', note: 'What it becomes on mobile' }, { id: 'ui:navigation-menu', note: 'Site navigation' }, { id: 'ui:tooltip', note: 'Collapsed labels' }],
    examples: [{ title: 'Application shell', code: '<SidebarProvider>\n  <Sidebar collapsible="icon">\n    <SidebarHeader>{/* brand */}</SidebarHeader>\n    <SidebarContent>\n      <SidebarGroup>\n        <SidebarGroupLabel>Workspace</SidebarGroupLabel>\n        <SidebarGroupContent>\n          <SidebarMenu>\n            <SidebarMenuItem>\n              <SidebarMenuButton asChild isActive tooltip="Dashboard">\n                <a href="/"><Home /><span>Dashboard</span></a>\n              </SidebarMenuButton>\n            </SidebarMenuItem>\n          </SidebarMenu>\n        </SidebarGroupContent>\n      </SidebarGroup>\n    </SidebarContent>\n    <SidebarRail />\n  </Sidebar>\n  <SidebarInset>\n    <SidebarTrigger />\n    <main>{children}</main>\n  </SidebarInset>\n</SidebarProvider>' }],
  },

  calendar: {
    tier: 'organisms', category: 'Forms', status: 'stable',
    intent: 'Pick a date when the surrounding days matter to the choice.',
    description: 'A react-day-picker wrapper styled with buttonVariants. Single, multiple and range selection modes.',
    whenToUse: ['Date selection where day of week or adjacency matters', 'Date ranges', 'Inside ui:popover as a date-picker field'],
    whenNotToUse: [
      'A known specific date the user can type faster — offer a text input too',
      'Dates far in the past, like a birth date — a year and month select is far quicker',
      'Where a relative choice would do — Today, Tomorrow, Next week',
    ],
    anatomy: [
      { part: 'Root', role: 'The month grid with navigation' },
      { part: 'CalendarDayButton', role: 'One day cell. Exported so you can decorate days.' },
    ],
    states: [
      { name: 'Default', trigger: 'Rest', note: 'Current month rendered' },
      { name: 'Selected', trigger: 'Matches selected', note: 'bg-primary text-primary-foreground' },
      { name: 'Today', trigger: 'Current date', note: 'bg-accent' },
      { name: 'Outside month', trigger: 'Leading or trailing days', note: 'text-muted-foreground, opacity reduced' },
      { name: 'Disabled', trigger: 'Matched by the disabled matcher', note: 'opacity-50, not selectable' },
      { name: 'Range middle', trigger: 'Between range ends', note: 'bg-accent with no rounding' },
    ],
    a11y: {
      role: 'grid', handledByRadix: false,
      keyboard: ['Arrow keys — move by day', 'PageUp/PageDown — move by month', 'Home/End — start or end of week', 'Enter or Space — select'],
      requiredAttributes: ['An accessible label on the calendar', 'aria-live announcement of the selected date'],
      notes: [
        'react-day-picker supplies grid semantics and keyboard navigation.',
        'Always offer a typed alternative. Keyboard-only users navigating months by arrow key is punishing for distant dates.',
        'Announce the selection in a live region — the visual highlight alone is not enough.',
        'Set the disabled matcher rather than allowing an invalid pick and rejecting it afterwards.',
      ],
    },
    agentRules: [
      'Pair with a text input for typed entry.',
      'Use the disabled matcher to prevent invalid selections up front.',
      'Announce selections in a live region.',
      'Inside ui:popover, render PopoverContent with className="w-auto p-0".',
    ],
    forbiddenUsage: ['Calendar as the only date-entry route', 'Allowing invalid dates then rejecting on submit', 'Using a day grid for distant historical dates'],
    related: [{ id: 'ui:popover', note: 'The usual host for a date-picker field' }, { id: 'ui:input', note: 'Typed entry alternative' }],
    examples: [{ title: 'Date picker field', code: '<Popover>\n  <PopoverTrigger asChild>\n    <Button variant="outline" className="w-[240px] justify-start">\n      <CalendarIcon className="mr-2 h-4 w-4" />\n      {date ? format(date, "PPP") : "Pick a date"}\n    </Button>\n  </PopoverTrigger>\n  <PopoverContent className="w-auto p-0" align="start">\n    <Calendar mode="single" selected={date} onSelect={setDate} disabled={{ before: new Date() }} />\n  </PopoverContent>\n</Popover>' }],
  },

  toast: {
    tier: 'organisms', category: 'Feedback', status: 'stable',
    intent: 'Confirm that something happened, without taking the user away from what they are doing.',
    description: 'Radix Toast primitives with swipe-to-dismiss and a default and destructive variant. The render host is ui:toaster; the queue is useToast.',
    whenToUse: ['Confirming a completed action', 'Non-blocking errors the user can act on later', 'Undo affordances after a reversible change'],
    whenNotToUse: [
      'Anything the user must read — toasts disappear and many users will miss them',
      'Errors that block progress — use ui:alert, which stays',
      'Anything needing a decision — use ui:alert-dialog',
      'Long messages, or several at once',
    ],
    compound: {
      root: 'ToastProvider',
      parts: [
        { name: 'ToastProvider', parent: null, required: true, note: 'Supplied by ui:toaster' },
        { name: 'ToastViewport', parent: 'ToastProvider', required: true, note: 'Where toasts render. Supplied by ui:toaster.' },
        { name: 'Toast', parent: 'ToastProvider', required: true },
        { name: 'ToastTitle', parent: 'Toast', required: false },
        { name: 'ToastDescription', parent: 'Toast', required: false },
        { name: 'ToastAction', parent: 'Toast', required: false, note: 'A single action, typically Undo. altText is required.' },
        { name: 'ToastClose', parent: 'Toast', required: false },
      ],
    },
    variantGuidance: {
      default: 'Confirmations and neutral information.',
      destructive: 'Failures. Consider whether a ui:alert that stays would serve better.',
    },
    states: [
      { name: 'Entering', trigger: 'Added to the queue', note: 'Slides in from the top on mobile, bottom-right on desktop' },
      { name: 'Visible', trigger: 'During its duration', note: 'Timer paused on hover and focus' },
      { name: 'Swiping', trigger: 'Drag right', note: 'Follows the pointer' },
      { name: 'Dismissed', trigger: 'Timeout, swipe or close', note: 'Animates out' },
    ],
    a11y: {
      role: 'status', handledByRadix: true,
      keyboard: ['F8 — focus the toast viewport', 'Tab — reach actions once focused', 'Escape — dismiss'],
      requiredAttributes: ['altText on ToastAction'],
      notes: [
        'Radix announces toasts politely and pauses the timer on hover and focus.',
        'ToastAction requires altText — it is what screen-reader users hear as the alternative to the action.',
        'The default duration may be too short to read a long message. Keep toasts to one line.',
        'A dismissed toast is gone. Never put the only copy of important information in one.',
      ],
    },
    agentRules: [
      'One line. Keep it short enough to read before it goes.',
      'ToastAction requires altText.',
      'At most one action per toast.',
      'Persistent errors belong in ui:alert.',
      'Never put unrecoverable information in a toast.',
    ],
    forbiddenUsage: ['Critical information in a toast', 'Multiple actions in one toast', 'ToastAction with no altText', 'Long multi-paragraph toasts'],
    related: [{ id: 'ui:toaster', note: 'The render host — required' }, { id: 'ui:alert', note: 'Persistent messages' }, { id: 'ui:sonner', note: 'The alternative toast system — pick one' }],
    examples: [{ title: 'Undo toast', code: 'toast({\n  title: "Project archived",\n  description: "Apollo moved to the archive.",\n  action: <ToastAction altText="Undo archiving Apollo" onClick={undo}>Undo</ToastAction>,\n})' }],
  },

  toaster: {
    tier: 'templates', category: 'Feedback', status: 'stable',
    intent: 'The one place toasts actually render.',
    description: 'The render host for ui:toast. Subscribes to the useToast queue and maps it to Toast elements. Mount once at the app root.',
    whenToUse: ['Once, at the application root, whenever ui:toast is used anywhere'],
    whenNotToUse: ['More than once — duplicate Toasters render duplicate toasts', 'Inside a route or a conditionally rendered branch'],
    anatomy: [{ part: 'Root', role: 'ToastProvider plus ToastViewport, with the queue mapped to Toast elements' }],
    states: [
      { name: 'Empty', trigger: 'No toasts queued', note: 'Viewport present but empty' },
      { name: 'Populated', trigger: 'Toasts queued', note: 'Renders in order, capped by the queue limit in use-toast.ts' },
    ],
    a11y: {
      role: 'region', handledByRadix: true,
      keyboard: ['F8 — focus the viewport'],
      requiredAttributes: [],
      notes: ['Mount it at the root so toasts survive route changes.', 'Two Toasters means every toast appears twice.'],
    },
    agentRules: ['Mount exactly once, at the root.', 'Do not conditionally render it.', 'Pick either this or ui:sonner — not both. This is the default: it matches the rest of the library and enforces altText on toast actions.'],
    forbiddenUsage: ['Multiple Toaster instances', 'Conditional mounting', 'Running alongside ui:sonner'],
    related: [{ id: 'ui:toast', note: 'The primitives it renders' }, { id: 'ui:sonner', note: 'The alternative — choose one' }],
    examples: [{ title: 'Root mount', code: '// src/App.tsx\n<>\n  <Routes>{/* … */}</Routes>\n  <Toaster />\n</>' }],
  },

  sonner: {
    tier: 'templates', category: 'Feedback', status: 'stable',
    intent: 'The same job as ui:toaster, through a different library with a simpler imperative API.',
    description: 'A Sonner wrapper themed to shadcn tokens. Exports SonnerToaster — deliberately not Toaster, so it cannot collide with ui:toaster at an import site. Reads the theme from the dark class this app actually toggles.',
    whenToUse: ['When you prefer Sonner\'s imperative toast() API and stacking behaviour', 'Promise-based toasts that resolve to success or failure'],
    whenNotToUse: [
      'Alongside ui:toaster — running both produces two toast systems and two viewports',
      'When you need the Radix action and altText contract',
    ],
    anatomy: [{ part: 'Root', role: 'The Sonner Toaster, themed with shadcn CSS variables' }],
    states: [
      { name: 'Empty', trigger: 'No toasts', note: 'Nothing visible' },
      { name: 'Stacked', trigger: 'Several toasts', note: 'Sonner stacks and collapses them' },
    ],
    a11y: {
      role: 'region', handledByRadix: false,
      keyboard: ['Sonner supplies its own focus and dismissal handling'],
      requiredAttributes: [],
      notes: [
        'Sonner manages its own announcements. Verify against your screen-reader targets — the contract differs from Radix Toast, which requires altText on every action.',
        'Theme is read from the dark class on <html> via a MutationObserver, matching tailwind darkMode: ["class"]. The upstream shadcn snippet reads next-themes, which no provider here mounts — it would report "system" regardless and render light toasts on a dark page.',
      ],
    },
    agentRules: [
      'Choose Sonner or ui:toaster. Never both — two systems means every toast appears twice.',
      'The export is SonnerToaster, not Toaster. That is deliberate.',
      'Sonner actions carry no altText requirement. If you need that accessibility contract, use ui:toast.',
    ],
    forbiddenUsage: ['Running alongside ui:toaster', 'Re-aliasing SonnerToaster back to Toaster'],
    related: [{ id: 'ui:toaster', note: 'The Radix-based alternative' }, { id: 'ui:toast', note: 'The Radix primitives' }],
    examples: [{ title: 'Mount once, then call imperatively', code: '// src/App.tsx — one system only\n<SonnerToaster />\n\n// anywhere\nimport { toast } from "sonner"\ntoast.success("Project archived", {\n  action: { label: "Undo", onClick: undo },\n})' }],
    gaps: [
      'Only one toast system may be mounted. Nothing enforces that at build time — it is a review concern.',
    ],
  },
}
